services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
    repoPath: frontend    
    envVars:
      - key: GENERATE_SOURCEMAP
        value: false
      - key: REACT_APP_API_URL
        value: https://books-backend-fyr1.onrender.com/api  

  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    repoPath: backend     
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://skayanokoji7:Skpika2507($)@cluster-1.qrqwgfm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-1"
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        value: SurajKumarthedevil
      - key: EMAIL_USER
        value: surajkumar.sk.pika.0807@gmail.com
      - key: EMAIL_PASS
        value: tlrl ckym jhbu jybu
      - key: FRONTEND_URL
        value: https://books-frontend-xu1t.onrender.com  
